import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css"
import Navbar from "@/components/Navbar"
import { Separator } from "@/components/ui/separator"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SplitBills",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Separator orientation="horizontal" />
        {children}
      </body>
    </html>
  );
}
